In [1]:
import tensorflow as tf
from tensorflow.compat.v1.keras.backend import set_session
from tensorflow.keras import backend as K

import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
x = tf.constant([[1., 2., 3., 4.],
                 [5., 6., 7., 8.],
                 [9., 10., 11., 12.],
                 [13., 14., 15., 16.]])
x

<tf.Tensor: id=1, shape=(4, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)>

In [5]:
x = tf.reshape(x, [1, 4, 4, 1])
x

<tf.Tensor: id=3, shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]],

        [[13.],
         [14.],
         [15.],
         [16.]]]], dtype=float32)>

In [6]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid')
max_pool_2d(x)

<tf.Tensor: id=5, shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 6.],
         [ 7.],
         [ 8.]],

        [[10.],
         [11.],
         [12.]],

        [[14.],
         [15.],
         [16.]]]], dtype=float32)>

In [7]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid')
max_pool_2d(x)

<tf.Tensor: id=6, shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 6.],
         [ 8.]],

        [[14.],
         [16.]]]], dtype=float32)>

In [10]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), padding='same')
max_pool_2d(x)

<tf.Tensor: id=9, shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 6.],
         [ 8.]],

        [[14.],
         [16.]]]], dtype=float32)>